### ISSUE TITLE
Fail to unzip a ZIP created by SBT

### ISSUE THREAD

**Issue by michaelyaakoby** [pathikrit/better-files#112]
Hi, I'm trying to unzip a ZIP file created using SBT and File.unzip is failing with the following exception:
```
Exception in thread "main" java.nio.file.NoSuchFileException: C:\work\asterix\updates\unzipped\ginger\xcp\xcp
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:230)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.createFile(Files.java:632)
	at better.files.File.createIfNotExists(File.scala:131)
	at better.files.File.createChild(File.scala:113)
	at better.files.File$$anonfun$unzipTo$1$$anonfun$apply$3.apply(File.scala:782)
	at better.files.File$$anonfun$unzipTo$1$$anonfun$apply$3.apply(File.scala:781)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:462)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at better.files.File$$anonfun$unzipTo$1.apply(File.scala:781)
	at better.files.File$$anonfun$unzipTo$1.apply(File.scala:780)
	at better.files.Implicits$CloseableOps$$anon$1.foreach(Implicits.scala:180)
	at better.files.File.unzipTo(File.scala:780)

```

Seems like in this directory a file entry was added before the directory so the "unZip" function is trying to created a file in a nonexistent dir.

[b.zip](https://github.com/pathikrit/better-files/files/772282/b.zip)

Thanks,
Michael

**Comment by pathikrit** [comment]
Fixed in https://github.com/pathikrit/better-files/pull/100

**Comment by michaelyaakoby** [comment]
Awesome, thanks.
BTW, better-files is really awesome.
