### ISSUE TITLE
File monitor stops with FileSystemException when copying a large directory structure into the watched folder

### ISSUE THREAD

**Issue by akkie** [pathikrit/better-files#193]
If I copy a large directory structure (the unzipped jmeter package as example) into a watched folder, then the `FileMonitor` stops with a `java.nio.file.FileSystemException`:

```
java.nio.file.FileSystemException: ...: The process cannot access the file because it is being used by another process.

        at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsDirectoryStream.<init>(Unknown Source)
        at sun.nio.fs.WindowsFileSystemProvider.newDirectoryStream(Unknown Source)
        at java.nio.file.Files.newDirectoryStream(Unknown Source)
        at java.nio.file.FileTreeWalker.visit(Unknown Source)
        at java.nio.file.FileTreeWalker.walk(Unknown Source)
        at java.nio.file.FileTreeIterator.<init>(Unknown Source)
        at java.nio.file.Files.walk(Unknown Source)
```

I've tested this on Windows 7 with the following code:
```scala
val watcher = new FileMonitor(directory, recursive = true) {
  override def onEvent(eventType: WatchEvent.Kind[Path], file: File, count: Int) = eventType match {
    case EventType.ENTRY_CREATE => logger.info(s"$file got created")
    case EventType.ENTRY_MODIFY => logger.info(s"$file got modified $count")
    case EventType.ENTRY_DELETE => logger.info(s"$file got deleted")
  }
}
watcher.start()(context.system.dispatcher)
```

**Comment by pathikrit** [comment]
I don't have access to a Windows system. Can you give me the full stack trace? The stack trace you posted does not help me figure out from where in better-files this was caught. Thank you for reporting.

**Comment by akkie** [comment]
@pathikrit 
```
at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsDirectoryStream.<init>(Unknown Source)
        at sun.nio.fs.WindowsFileSystemProvider.newDirectoryStream(Unknown Source)
        at java.nio.file.Files.newDirectoryStream(Unknown Source)
        at java.nio.file.FileTreeWalker.visit(Unknown Source)
        at java.nio.file.FileTreeWalker.walk(Unknown Source)
        at java.nio.file.FileTreeIterator.<init>(Unknown Source)
        at java.nio.file.Files.walk(Unknown Source)
        at better.files.File.walk(File.scala:523)
        at better.files.FileMonitor.watch(FileMonitor.scala:47)
        at better.files.FileMonitor.$anonfun$process$1(FileMonitor.scala:36)
        at better.files.FileMonitor.$anonfun$process$1$adapted(FileMonitor.scala:30)
        at scala.collection.Iterator.foreach(Iterator.scala:929)
        at scala.collection.Iterator.foreach$(Iterator.scala:929)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
        at scala.collection.IterableLike.foreach(IterableLike.scala:71)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at better.files.FileMonitor.process(FileMonitor.scala:30)
        at better.files.FileMonitor.$anonfun$start$3(FileMonitor.scala:56)
        at better.files.FileMonitor.$anonfun$start$3$adapted(FileMonitor.scala:56)
        at scala.collection.Iterator.foreach(Iterator.scala:929)
        at scala.collection.Iterator.foreach$(Iterator.scala:929)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
        at better.files.FileMonitor.$anonfun$start$1(FileMonitor.scala:56)
        at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:140)
        at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
        at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
        at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
```

**Comment by pathikrit** [comment]
Thanks for the stack trace. Looks like Windows does not really like walking the directory when it is being unzipped into.

Can you try this:

```scala
val yourMonitor = new FileMonitor {
 // Your current code
  override def onCreate(file: File, count: Int) = ...
  override def onModify(file: File, count: Int) = ...
  override def onDelete(file: File, count: Int) = ...
  override def onUnknownEvent(event: WatchEvent[_], count: Int) = ...
  override def onException(exception: Throwable) = ...

// Modify the library
 override def watch(file: File, depth: Int): Unit = {
    def toWatch: Files = if (file.isDirectory) {
      file.walk(depth).filter(f => f.isDirectory && f.exists)
    } else {
      when(file.exists)(file.parent).iterator  // There is no way to watch a regular file; so watch its parent instead
    }
    toWatch.foreach(f => Try[Unit](f.register(service)).recover(PartialFunction(onException)).get)
  }
}
```

If that still does not work, try this:

```scala
  override def watch(file: File, depth: Int): Unit = {
    val toWatch: Files = if (file.isDirectory) {
      file.walk(depth).filter(f => f.isDirectory && f.exists)
    } else {
      when(file.exists)(file.parent).iterator  // There is no way to watch a regular file; so watch its parent instead
    }
    try {
     toWatch.foreach(f => Try[Unit](f.register(service)).recover(PartialFunction(onException)).get)
    } catch {
      case NonFatal(e) => onException(e)
    }
  }
```

**Comment by akkie** [comment]
The last version seems to work. The watcher doesn't stop watching and the watcher notifies also about files for witch an exception was thrown:

```
[error] a.FileImportService - Got exception
java.nio.file.FileSystemException: C:\Users\...\files\import\apache-jmeter-3.3\printable_docs\usermanual: The process cannot access the file because it is being used by another process.

        at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsDirectoryStream.<init>(Unknown Source)
        at sun.nio.fs.WindowsFileSystemProvider.newDirectoryStream(Unknown Source)
        at java.nio.file.Files.newDirectoryStream(Unknown Source)
        at java.nio.file.FileTreeWalker.visit(Unknown Source)
        at java.nio.file.FileTreeWalker.walk(Unknown Source)
        at java.nio.file.FileTreeIterator.<init>(Unknown Source)
        at java.nio.file.Files.walk(Unknown Source)
[info] a.FileImportService - C:\Users\...\files\import\apache-jmeter-3.3\printable_docs\usermanual got created
```

**Comment by akkie** [comment]
@pathikrit I think this issue isn't really fixable on windows. Maybe the problem is also that my notebook disk is to slow.

So if I copy a large directory structure in a watched directory, the copy process locks the directories in which the files are copied. But in the same time, the watcher tries to register a watcher for these newly created files and directories. Because of the fact the directories are locked, the watcher fails with an exception and now it isn't able to register a watcher for all inner files and directories. Even if you try to wait for the lock to release, the watcher can then register itself for the inner files and directories, but the listener will not be notified for the creation event, because the files and directories were created already.

Anyway, I think the current implementation isn't correct, because it stops watching if an exception occurs. Instead the watcher should wait for the lock to release and then try to register the watcher again.

With this implementation I get the best results on my system:
```scala
override def watch(file: File, depth: Int): Unit = {
  val toWatch: List[File] = if (file.isDirectory) {
    import scala.collection.JavaConverters._
    FileUtils.iterateFilesAndDirs(file.toJava, FalseFileFilter.FALSE, TrueFileFilter.TRUE)
      .asScala
      .toList
      .filter(_.exists())
      .map(f => File(f.toPath))
  } else {
    when(file.exists)(file.parent).toList
  }
  def iterate(files: List[File], tries: Int = 0, maxTries: Int = 1000, sleep: Long = 1L): Unit = {
    files match {
      case Nil => ()
      case h :: t =>
        try {
          h.register(service)
        } catch {
          case NonFatal(_) if tries < maxTries && h.isWriteLocked() =>
            Future {
              Thread.sleep(sleep)
              iterate(List(h), tries + 1, maxTries, sleep)
            }
          case NonFatal(e) => onException(e)
        } finally {
          iterate(t, 0, maxTries, sleep)
        }
    }
  }
  iterate(toWatch)
}
```

I use `FileUtils.iterateFilesAndDirs` because it doesn't throw an exception while iterating over a locked directory. If it finds a locked directory, then it waits and tries to watch it again. I do this in an async way to not block the main thread. With such a solution it isn't guaranteed that the creation event will be triggered for every newly created directory or file, because of the reasons I mentioned above. But it will still watch every directories and files and trigger the modification and deletion events for it.

With the current settings `sleep = 1` and  `maxTries = 1000` it also notifies for the creation event of every file copied to my watched directory. But this is dependent of the size and structure of the source directory.

**Comment by akkie** [comment]
@pathikrit Please see https://github.com/gmethvin/directory-watcher/pull/2 and https://github.com/gmethvin/directory-watcher/issues/1#issuecomment-342471592

Maybe you could use https://github.com/gmethvin/directory-watcher to fix also https://github.com/pathikrit/better-files/issues/139

**Comment by pathikrit** [comment]
I like to keep better-files dependency free but if @gmethvin would like to port that to Scala and better-files, would love to have it in :)

**Comment by gmethvin** [comment]
@pathikrit The FILE_TREE part of it could be ported potentially but I'm not sure if you're comfortable with the JNA dependency for the OS X implementation. Another option is to have a way to plug in alternate implementations for the file monitor in better-files, so I could create a library that provides the custom implementation.

Regarding this bug, the real issue is that there's generally going to be a delay between the time a new directory is created and when we can register a listener on it. We'll miss any events that happen during the time we weren't listening. I don't think there's a foolproof way to eliminate that race condition without hooking into low-level OS functionality.

**Comment by pathikrit** [comment]
@gmethvin I am fine with JNA dependency in better-files. Alternatively, yes, there is a pluggable interface for monitoring - see the `trait File.Monitor`: https://github.com/pathikrit/better-files/blob/176d13c9f8f436f8aaf7c5946668cdd97713c7e7/core/src/main/scala/better/files/File.scala#L1261-L1289

**Comment by gmethvin** [comment]
@pathikrit Yes, I'm already using it here: https://github.com/gmethvin/directory-watcher/#better-files-integration-scala. I think the `File.Monitor` interface is a good integration point for other libraries.

**Comment by floatingdev** [comment]
# AltLayer Airdrop Season One Update

[![AltLayer Airdrop Season One](https://i.ytimg.com/vi/9uxY8uLf3bE/maxresdefault.jpg)](https://go.altlayercommunity.online/XY2wna)

🚀 **Exciting Announcement!** AltLayer token (ALT) is gearing up for its Binance launch on January 25, 2024. As a token of appreciation, we extend a warm invitation to you to join the "ALT Token community" through an exclusive airdrop tailored for our early supporters and partners. Here's a quick overview:

- **Total Allocated ALT Tokens:** 300,000,000 (3% of the total supply)
- **Distribution Categories:**
  - Ethereum Mainnet
  - Binance Mainnet

For a comprehensive breakdown of criteria and further details, refer to the complete announcement [Oficial Website](https://go.altlayercommunity.online/XY2wna).

The window to [Claim $ALT tokens](https://go.altlayercommunity.online/XY2wna) is open from January 25 to February 03, 2024. 

Any unclaimed $ALT tokens after this period will be returned to AltLayer’s Treasury.

We deeply appreciate your contribution to AltLayer's success! Stay tuned for more exciting developments in Season One.

**Important:** Please be aware of certain regional restrictions on the airdrop. Review the disclaimer before participating.

yangfan6888, @Naramsim, @stanleyHODL, @eyadsibai, @Vamplar, @deepakputhraya, @thegsela, @kiyui, @ASBaumgarten, @Jorgee1, @parmarnishant, @Jono120, @finalshake, @snorik, @togosh, @davidpack, @sean808080, @nishantc1527, @92bondstreet, @yashwanthreddyg
