### ISSUE TITLE
Error when trying to read resource from jar

### ISSUE THREAD

**Issue by tlangs** [pathikrit/better-files#214]
When trying to read a resource from a jar assembled by SBT, `File.resource("dir/filename")` throws the following stacktrace: 
```
java.nio.file.FileSystemNotFoundException: null
        at com.sun.nio.zipfs.ZipFileSystemProvider.getFileSystem(ZipFileSystemProvider.java:171)
        at com.sun.nio.zipfs.ZipFileSystemProvider.getPath(ZipFileSystemProvider.java:157)
        at java.nio.file.Paths.get(Paths.java:143)
        at better.files.File$.apply(File.scala:1142)
        at better.files.File$.apply(File.scala:1139)
        at better.files.File$.resource(File.scala:1061)
        at org.broadinstitute.dsp.pipelines.tester.HybridSelectionTester.<init>(HybridSelectionTester.scala:62)
        at org.broadinstitute.dsp.pipelines.commandline.WorkflowTester$HybridSelection$.getTester(WorkflowTester.scala:55)
        at org.broadinstitute.dsp.pipelines.commandline.Config.getTester(Config.scala:27)
        at org.broadinstitute.dsp.pipelines.WorkflowTest$.$anonfun$main$1(WorkflowTest.scala:31)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.util.Try$.apply(Try.scala:209)
        at org.broadinstitute.dsp.pipelines.WorkflowTest$.main(WorkflowTest.scala:21)
        at org.broadinstitute.dsp.pipelines.WorkflowTest.main(WorkflowTest.scala)
```

I looked at the source for `File.resource()` and it looks like the error comes from using `getResource` in the classLoader instead of `getResourceAsStream`

**Comment by pathikrit** [comment]
Try using: `getResourceAsStream` util in better-files: https://github.com/pathikrit/better-files/blob/176d13c9f8f436f8aaf7c5946668cdd97713c7e7/core/src/main/scala/better/files/package.scala#L34
