### ISSUE TITLE
ResourceSpec failing in Scala 2.12 community build

### ISSUE THREAD

**Issue by SethTisue** [pathikrit/better-files#236]
seen at e.g. https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/2813/consoleFull

```
[better-files] [info] ResourceSpec:
[better-files] [info] Resource
[better-files] [info] - can look up from the context class loader
[better-files] [info] - can look up from a specified class loader *** FAILED ***
[better-files] [info]   java.net.MalformedURLException: no protocol: ../
[better-files] [info]   at java.net.URL.<init>(URL.java:593)
[better-files] [info]   at java.net.URL.<init>(URL.java:490)
[better-files] [info]   at better.files.ResourceSpec.$anonfun$new$2(ResourceSpec.scala:23)
[better-files] [info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[better-files] [info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[better-files] [info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[better-files] [info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[better-files] [info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[better-files] [info]   at org.scalatest.FlatSpecLike$$anon$1.apply(FlatSpecLike.scala:1682)
[better-files] [info]   at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
[better-files] [info]   ...
[better-files] [info] - can look up from the call site *** FAILED ***
[better-files] [info]   java.lang.NullPointerException:
[better-files] [info]   at better.files.File$.apply(File.scala:1354)
[better-files] [info]   at better.files.Resource.asFile(Resource.scala:41)
[better-files] [info]   at better.files.Resource$.asFile(Resource.scala:64)
[better-files] [info]   at better.files.ResourceSpec.$anonfun$new$3(ResourceSpec.scala:33)
[better-files] [info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[better-files] [info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[better-files] [info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[better-files] [info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[better-files] [info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[better-files] [info]   at org.scalatest.FlatSpecLike$$anon$1.apply(FlatSpecLike.scala:1682)
[better-files] [info]   ...
[better-files] [info] - can look up from a statically-known type *** FAILED ***
[better-files] [info]   java.lang.NullPointerException:
[better-files] [info]   at better.files.File$.apply(File.scala:1354)
[better-files] [info]   at better.files.Resource.asFile(Resource.scala:41)
[better-files] [info]   at better.files.ResourceSpec.$anonfun$new$4(ResourceSpec.scala:42)
[better-files] [info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[better-files] [info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[better-files] [info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[better-files] [info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[better-files] [info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[better-files] [info]   at org.scalatest.FlatSpecLike$$anon$1.apply(FlatSpecLike.scala:1682)
[better-files] [info]   at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
[better-files] [info]   ...
[better-files] [info] - can look up from a java.lang.Class *** FAILED ***
[better-files] [info]   java.lang.NullPointerException:
[better-files] [info]   at better.files.File$.apply(File.scala:1354)
[better-files] [info]   at better.files.Resource.asFile(Resource.scala:41)
[better-files] [info]   at better.files.ResourceSpec.$anonfun$new$5(ResourceSpec.scala:50)
[better-files] [info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[better-files] [info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[better-files] [info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[better-files] [info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[better-files] [info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[better-files] [info]   at org.scalatest.FlatSpecLike$$anon$1.apply(FlatSpecLike.scala:1682)
[better-files] [info]   at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
[better-files] [info]   ...
[better-files] [info] - can look up a file in another package *** FAILED ***
[better-files] [info]   java.lang.NullPointerException:
[better-files] [info]   at better.files.File$.apply(File.scala:1354)
[better-files] [info]   at better.files.Resource.asFile(Resource.scala:41)
[better-files] [info]   at better.files.ResourceSpec.$anonfun$new$6(ResourceSpec.scala:56)
[better-files] [info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[better-files] [info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[better-files] [info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[better-files] [info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[better-files] [info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[better-files] [info]   at org.scalatest.FlatSpecLike$$anon$1.apply(FlatSpecLike.scala:1682)
[better-files] [info]   at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
[better-files] [info]   ...
```

I will work around it for now for freezing better-files at a commit from a week or two ago

**Comment by pathikrit** [comment]
Sorry, we are working on something (see #232). Will disable this for now on master.

**Comment by SethTisue** [comment]
thx! https://github.com/scala/community-builds/commit/f7a0978cca63001483a01a78ee80e94c4452b016
