### ISSUE TITLE
Better exceptions

### ISSUE THREAD

**Issue by borissmidt** [pathikrit/better-files#404]
Hey i really like the better-files library it truly is one of the best libraries i've ever used for dealing with files.

There are still some  java parts that aren't fully wrapped for example:
`File("/some/dir/").lines ` returns the exception `java.io.IOException: Is a directory`
It would be nice if it returned `java.io.IOException: Is a directory, "/some/dir/"` instead

Otherwise i have to wrap everything to catch the exception and to know the file name at that point and to know my programming error.

**Comment by pathikrit** [comment]
Hi!
`better-files` is just delegating to Java NIO and I don't get this info from the Java NIO package itself. See:

```
> import java.nio.file.{Files, Paths}
> Files.readAllLines(Paths.get("/tmp"))

java.io.IOException: Is a directory
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.read(FileDispatcherImpl.java:46)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:197)
	at sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:159)
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:65)
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:109)
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:103)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.io.BufferedReader.readLine(BufferedReader.java:324)
	at java.io.BufferedReader.readLine(BufferedReader.java:389)
	at java.nio.file.Files.readAllLines(Files.java:3205)
	at java.nio.file.Files.readAllLines(Files.java:3242)

```

**Comment by borissmidt** [comment]
Would a pr be welcome which changes the message?

**Comment by borissmidt** [comment]
for example this could be added then you don't change the exception nor is it noisy:
 ```
 private def withPathInfo[T](f: =>T): T = try{
     f
  } catch {
    case e: Throwable =>
      e.addSuppressed(PathInfo(path))
      throw e
  }

case class PathInfo(path: Path) extends RuntimeException(s"$path"){
  override def getStackTrace = Array()

  override def printStackTrace(): Unit = {}
}

```


resulting in, where 'hello' is the file: 
```
withPathInfo(thorws)
java.lang.RuntimeException: hello
  at .thorws(<console>:11)
  at .$anonfun$res1$1(<console>:14)
  at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
  at .withFileNameInException(<console>:14)
  ... 28 elided
  Suppressed: PathInfo: hello
```
