### ISSUE TITLE
(3.9.0 regression): NoSuchMethodError when reading contentAsString on JDK8

### ISSUE THREAD

**Issue by hugo-vrijswijk** [pathikrit/better-files#417]
Hi, when running on JDK 8 with better-files on 3.9.0, I get a NoSuchMethodError when calling File#contentAsString. On JDK11 or better-files 3.8.0 no error occurs. The stacktrace:

```
java.lang.NoSuchMethodError: java.nio.ByteBuffer.rewind()Ljava/nio/ByteBuffer;
  at better.files.UnicodeDecoder.decode(UnicodeCharset.scala:50)
  at better.files.UnicodeDecoder.decodeLoop(UnicodeCharset.scala:64)
  at java.nio.charset.CharsetDecoder.decode(CharsetDecoder.java:579)
  at java.lang.StringCoding.decode(StringCoding.java:235)
  at java.lang.String.<init>(String.java:463)
  at java.lang.String.<init>(String.java:515)
  at better.files.File.contentAsString(File.scala:316)
  at stryker4s.report.mapper.MutantRunResultMapper.fileContentAsString(MutantRunResultMapper.scala:59)
  at stryker4s.report.mapper.MutantRunResultMapper.toMutationTestResult(MutantRunResultMapper.scala:28)
  at stryker4s.report.mapper.MutantRunResultMapper.$anonfun$toMutationTestResultMap$2(MutantRunResultMapper.scala:23)
  ...
```

Logs: https://github.com/stryker-mutator/stryker4s/pull/460/checks?check_run_id=678999661#step:6:1396

Line in code where error occurs: https://github.com/stryker-mutator/stryker4s/blob/master/core/src/main/scala/stryker4s/report/mapper/MutantRunResultMapper.scala#L59

**Comment by slandelle** [comment]
Proposed fix in #418

**Comment by pathikrit** [comment]
Released v3.9.1. See log on Travis CI to make sure it was released via JDK8 - https://travis-ci.com/github/pathikrit/better-files

**Comment by slandelle** [comment]
thanks!

**Comment by hugo-vrijswijk** [comment]
I can confirm this now works on jdk8. Thanks for the quick response and fix!
